import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav/Nav";

import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MEDI Manager",
  description: "Generated by George Bell",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="pageContainer">
          <Nav />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
